FROM redis:alpine

# Expose the Redis port
EXPOSE 6379

# Copy the redis-init.sh script to the image
COPY redis-init.sh /usr/local/bin/redis-init.sh

# Make the script executable
RUN chmod +x /usr/local/bin/redis-init.sh

# Set the script as the entrypoint
ENTRYPOINT ["/usr/local/bin/redis-init.sh"]
