FROM golang:1.22.2

WORKDIR /usr/src/app

COPY scripts/wait-for-it.sh .
RUN chmod +x wait-for-it.sh

COPY go.mod go.sum ./
RUN go mod download

COPY scraper/go.mod scraper/go.sum ./scraper/
COPY scraper/src ./scraper/src

WORKDIR /usr/src/app/scraper/src

RUN go build -o /scraper
