# Django app using Python 3.11
from python:3.11

RUN pip install gunicorn

COPY requirements.txt /app/requirements.txt
WORKDIR /app

RUN pip install -r requirements.txt

# COPY cuapi/ /app/cuapi

COPY cuapi/ /app/cuapi

COPY scripts/backend-entrypoint.sh /app/cuapi/backend-entrypoint.sh

WORKDIR /app/cuapi

RUN chmod +x backend-entrypoint.sh
