FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy requirements.txt and install dependencies
COPY backend/requirements.txt .
RUN pip install -r requirements.txt

# Copy the backend directory contents into the container at /usr/src/app
COPY backend .

COPY scripts/wait-for-it.sh .
RUN chmod +x wait-for-it.sh

# Set environment variables
ENV PYTHONPATH=/usr/src/app/src
