FROM nginx:latest

# Install necessary packages
RUN apt-get update && apt-get install -y netcat-openbsd
RUN apt-get update \
    && apt-get install -y certbot python3-certbot-nginx

# Copy the Nginx configuration template
COPY config/nginx.conf.template /etc/nginx/nginx.conf.template

# Copy the modified startup script
COPY scripts/start-nginx.sh /start-nginx.sh
RUN chmod +x /start-nginx.sh

# Set up the entrypoint to use the startup script
CMD ["/start-nginx.sh"]
