# Generated by Django 5.0.6 on 2024-05-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='long_title',
            field=models.CharField(default='fsdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesection',
            name='short_title',
            field=models.CharField(default='fasfasdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesection',
            name='subject_code',
            field=models.CharField(default='fasdfad', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offering',
            name='long_title',
            field=models.CharField(default='fasdfa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offering',
            name='short_title',
            field=models.CharField(default='fasdfasd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offering',
            name='subject_code',
            field=models.CharField(default='fasdfasdf', max_length=100),
            preserve_default=False,
        ),
    ]
