# Generated by Django 5.0.6 on 2024-05-28 22:19

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_coursesection_long_title_coursesection_short_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offering",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
