# Generated by Django 5.0.6 on 2024-06-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_offering_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='description',
            field=models.TextField(default='fasdfads'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offering',
            name='description',
            field=models.TextField(default='fadsfasfd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='course_description',
            field=models.TextField(),
        ),
    ]
