# Generated by Django 5.0.6 on 2024-06-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursesection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursedetails',
            unique_together={('crn', 'registration_term')},
        ),
    ]
